#!/usr/bin/env python3
# =============================================================================
# @file    load-mock-data
# @brief   Load some sample data for DIBS
# @created 2021-01-07
# @license Please see the file named LICENSE in the project directory
# @website https://github.com/caltechlibrary/dibs
# =============================================================================

from datetime import datetime, timedelta
from decouple import config
from os.path import dirname, join, isabs
from peewee import SqliteDatabase

from dibs.database import Item, Loan, History, Person
from dibs.settings import config

db_file = config('DATABASE_FILE')
if not isabs(db_file):
    db_file = join(dirname(config.config_file), db_file)

database = SqliteDatabase(db_file)

# Peewee autoconnects to the database if doing queries, but not for other ops.
database.connect()
database.create_tables([Item, Loan, History, Person])

# This next one is a demo item.  We provide a manifest in ./manifests/ and
# it references an open copy of the book at the Wellcome Collection in the UK.
Item.create(barcode    = '350470000363458',
            item_id    = '514607',
            item_page  = 'https://caltech.tind.io/record/514607',
            title      = 'The Biocrats',
            author     = 'Gerald Leach',
            year       = '1970',
            publisher  = 'McGraw-Hill',
            edition    = 'First',
            num_copies = 1,
            duration   = 6,
            notes      = ('This is just a random book chosen because it was'
                          + ' the only title we could find in both a public'
                          + ' external IIIF server and in our Caltech catalog'),
            ready      = True,
)

print('-'*50)
print('Now use people-manager to add users')
print('-'*50)
